name: CacPlugin
main: fr.cactt4ck.cacplugin.CacPlugin
version: v1.0
api-version: "1.14"
authors: [CacTt4ck, _thender_]
description: Un plugin avec toutes sortes de commandes !
database: false
load: STARTUP
commands:

  bc:
      description: Envoyer un message à tout le serveur.
      usage: /<command> <message>
      permission: cacplugin.bc

  tp:
      description: Téléporte à un autre joueur
      usage: /<command> <player> | /<command> <player> <player>
      permission: cacplugin.tp

  tph:
      description: Téléporte un joueur à vous
      usage: /<command> <player>
      permission: cacplugin.tph

  tpall:
      description: Téléporte tous les joueurs à vous
      usage: /<command>

  gm:
      description: Change de mode de jeu
      usage: /<command>
      permission: cacplugin.gm

  exit:
      description: Permet de se déconnecter du serveur
      usage: /<command>

  punish:
      description: Permet de punir un joueur
      usage: /<command> <joueur>

  login:
      description: Permet de s'authentifier avec son mot de passe
      usage: /<command> <mot de passe>
      aliases: [lg, log]

  register:
      description: Permet de s'authentifier avec son mot de passe
      usage: /<command> <mot de passe> <mot de passe>
      aliases: [reg]

  changepass:
      description: Permet de s'authentifier avec son mot de passe
      usage: /<command> <nouveau mot de passe> <nouveau mot de passe>

  money:
      description: Permet d'utiliser les commandes d'économie
      aliases: [balance, bal]

  pay:
      description: Permet de payer un joueur
      usage: /<command> <joueur> <pièces d'or>

  back:
      description: Vous téléporte à votre mort.
      usage: /<command>

  setspawn:
      description: Défini le spawn.
      usage: /<command>
      aliases: [ss, sspawn]

  spawn:
      description: Vous téléporte au spawn.
      usage: /<command>
      aliases: [s]

  heal:
      description: Vous soigne.
      usage: /<command> | /<command> <joueur>

  feed:
      description: Vous rassasie.
      usage: /<command> | /<command> <joueur>

  disable:
      description: Désactive un plugin.
      usage: /<command> <plugin name>

  cacrl:
      description: Actualise la config de Cacplugin.
      aliases: [crl]

  spotter:
      description: Active/Désactive la récupération d'items.
      aliases: [spt]

  alert:
      description: Avertis un joueur.
      aliases: [al]
      usage: /<command> <joueur>

  sun:
      description: Met le temps clair.
      usage: /<command>

  rain:
      description: Met le temps pluvieux.
      usage: /<command>

  thunder:
      description: Met le temps orageux.
      usage: /<command>

  day:
      description: Met le jour.
      usage: /<command>

  night:
      description: Met la nuit.
      usage: /<command>

  midday:
      description: Met le temps à midi
      usage: /<command>

  randomtp:
      description: Vous téléporte à des coordonnées aléatoires.
      usage: /<command>

  home:
      description: Vous téléporte à votre home créé au préalable.
      usage: /<command> <home>

  sethome:
      description: Crée un home avec le nom que vous voulez.
      usage: /<command> <home>

  delhome:
      description: Supprime un home.
      usage: /<command> <home>

  msg:
      description: Envoie un message privé à un joueur.
      aliases: [tell, speak, say]
      usage: /<command> <joueur>

  remove:
      description: Enleve un joueur de la liste des personnes enregistrées dans le serveur.
      aliases: [rm]
      usage: /<command> <joueur>

  getpos:
      description: Récupère les coordonnées et le monde d'un joueur.
      usage: /<command> <joueur>

  clearchat:
      description: Clear le chat.
      aliases: [cc]
      usage: /<command>

  invsee:
      description: Ouvre l'inventaire d'un joueur.
      usage: /<command> <joueur>

  invcopy:
      description: Copie l'inventaire d'un joueur.
      usage: /<command> <joueur>

  popo:
      description: Applique l'effet désiré sur un joueur.
      usage: /<command> <effet> <durée en sec> <niveau de l'effet>

  furnace:
      description: Cuit l'item dans votre main automatiquement.
      usage: /<command>

permissions:
  cacplugin.*:
    description: Donne l'accès à toutes les commandes du plugin.
    children:
      cacplugin.bc: true
      cacplugin.rl: true
  cacplugin.bc:
     description: Permet l'utilisation de la commande /bc
     default: false